// =====================================================================
// Definición de los campos del formulario de afiliación.
// Cada campo indica: clave en la base de datos, etiqueta, tipo de control,
// si es obligatorio, longitud máxima y de qué tabla de referencia sale
// (cuando aplica). app.js usa esta lista para construir el formulario.
// =====================================================================

const CAMPOS_FORMULARIO = [
  { clave: "tipo_identificacion", etiqueta: "Tipo de identificación", tipo: "select", ref: "ref_tipo_identificacion", obligatorio: true },
  { clave: "identificacion", etiqueta: "Identificación empleado", tipo: "numero", obligatorio: true, ayuda: "Solo números" },
  { clave: "primer_nombre", etiqueta: "Primer nombre", tipo: "texto", obligatorio: true, maxLength: 15 },
  { clave: "segundo_nombre", etiqueta: "Segundo nombre", tipo: "texto", obligatorio: false, maxLength: 15 },
  { clave: "primer_apellido", etiqueta: "Primer apellido", tipo: "texto", obligatorio: true, maxLength: 15 },
  { clave: "segundo_apellido", etiqueta: "Segundo apellido", tipo: "texto", obligatorio: false, maxLength: 15 },
  { clave: "fecha_nacimiento", etiqueta: "Fecha de nacimiento", tipo: "fecha", obligatorio: true },
  { clave: "genero", etiqueta: "Género", tipo: "select", ref: "ref_sexo", obligatorio: true },
  { clave: "estado_civil", etiqueta: "Estado civil", tipo: "select", ref: "ref_estado_civil", obligatorio: true },
  { clave: "fecha_inicio_practica", etiqueta: "Fecha inicio práctica", tipo: "fecha", obligatorio: true },
  { clave: "fecha_final_practica", etiqueta: "Fecha final práctica", tipo: "fecha", obligatorio: true },
  { clave: "fecha_inicio_cobertura", etiqueta: "Fecha inicio de cobertura", tipo: "fecha-cobertura", obligatorio: true,
    ayuda: "Debe iniciar mínimo 2 días hábiles después de hoy" },
  { clave: "facultad_ur", etiqueta: "Facultad / Unidad", tipo: "select-facultad", ref: "ref_facultades", obligatorio: true },
  { clave: "facultad_axa", etiqueta: "Facultad AXA (derivado)", tipo: "derivado", obligatorio: true },
  { clave: "codigo_centro_trabajo", etiqueta: "Código centro de trabajo (derivado)", tipo: "derivado", obligatorio: true },
  { clave: "tipo_salario", etiqueta: "Tipo de salario", tipo: "select", ref: "ref_tipo_salario", obligatorio: true },
  { clave: "valor_salario", etiqueta: "Valor salario", tipo: "numero", obligatorio: true },
  { clave: "cargo", etiqueta: "Cargo", tipo: "texto", obligatorio: true, maxLength: 30 },
  { clave: "eps", etiqueta: "EPS", tipo: "select", ref: "ref_eps", obligatorio: true },
  { clave: "departamento", etiqueta: "Departamento", tipo: "select-departamento", obligatorio: true },
  { clave: "ciudad", etiqueta: "Ciudad", tipo: "select-ciudad", obligatorio: true },
  { clave: "ocupacion", etiqueta: "Ocupación", tipo: "autocompletar-ocupacion", obligatorio: true,
    ayuda: "Escribe para buscar o digita el nombre exacto" },
  { clave: "codigo_sucursal", etiqueta: "Código de sucursal", tipo: "select", ref: "ref_sucursales", obligatorio: true },
  { clave: "direccion", etiqueta: "Dirección (del estudiante)", tipo: "texto", obligatorio: true, maxLength: 60 },
  { clave: "telefono", etiqueta: "Teléfono", tipo: "texto", obligatorio: false, maxLength: 15 },
  { clave: "celular", etiqueta: "Celular", tipo: "texto", obligatorio: true, maxLength: 10, minLength: 10, ayuda: "Exactamente 10 dígitos" },
  { clave: "correo_ur", etiqueta: "Correo UR", tipo: "correo", obligatorio: true, maxLength: 60, ayuda: "Debe terminar en @urosario.edu.co" },
  { clave: "codigo_alto_riesgo", etiqueta: "Código alto riesgo", tipo: "select", ref: "ref_codigo_riesgo", obligatorio: true },
  { clave: "centro_costo", etiqueta: "Centro de costo (cargue pago ARL)", tipo: "texto", obligatorio: true },
  { clave: "orden_interna", etiqueta: "Orden interna (cargue pago ARL)", tipo: "texto", obligatorio: false },
  { clave: "nombre_centro_practica", etiqueta: "Nombre centro de práctica / actividad que conlleva afiliación", tipo: "texto-largo", obligatorio: false },
];

// Encabezados esperados en la plantilla de Excel para el cargue masivo
// (se normalizan quitando tildes/OBLIGATORIO/saltos de línea antes de comparar)
const ENCABEZADOS_PLANTILLA = {
  "tipo de identificacion": "tipo_identificacion",
  "identificacion empleado": "identificacion",
  "primer nombre": "primer_nombre",
  "segundo nombre": "segundo_nombre",
  "primer apellido": "primer_apellido",
  "segundo apellido": "segundo_apellido",
  "fecha de nacimiento": "fecha_nacimiento",
  "genero": "genero",
  "estado civil": "estado_civil",
  "fecha inicio practica": "fecha_inicio_practica",
  "fecha final practica": "fecha_final_practica",
  "fecha inicio de cobertura": "fecha_inicio_cobertura",
  "facultad": "facultad_ur",
  "tipo de salario": "tipo_salario",
  "valor salario": "valor_salario",
  "cargo": "cargo",
  "eps": "eps",
  "departamento": "departamento",
  "ciudad": "ciudad",
  "ocupacion": "ocupacion",
  "nit de empresa en mision": "nit_empresa",
  "codigo de sucursal": "codigo_sucursal",
  "codigo de centro de trabajo": "codigo_centro_trabajo",
  "direccion": "direccion",
  "telefono": "telefono",
  "celular": "celular",
  "correo electronico ur": "correo_ur",
  "codigo alto riesgo": "codigo_alto_riesgo",
  "centro de costo cargue pago arl": "centro_costo",
  "orden interna cargue pago arl": "orden_interna",
  "nombre centro de practica y/o actividad que conlleva a afiliacion": "nombre_centro_practica",
};
